before_commands:
    - "composer install --no-dev --prefer-dist"

tools:
    external_code_coverage:
        timeout: 1200
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        filter:
            paths: ["config/*", "public/*", "src/*", "test/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["data", "test", "vendor"]
    php_cs_fixer:
        enabled: true
        filter:
            paths: ["config/*", "public/*", "src/*", "test/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["data", "test", "vendor"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["data", "test", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["config/*", "public/*", "src/*", "test/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["config/*", "public/*", "src/*", "test/*"]
    sensiolabs_security_checker: true
