language: php

sudo: false

php:
    - 7.0
    - 7.1
    - nightly

matrix:
    fast_finish: true

    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer self-update
    - travis_retry composer global require hirak/prestissimo
    - travis_retry composer install --no-interaction --prefer-dist


before_script:
    - cp .env.dist .env
    - mkdir -p build/coverage
    - mkdir -p build/logs

script:
    - ./vendor/bin/grumphp run

after_script:
    - sh .travis.coverage.sh
