---
-
  hosts: webservers
  remote_user: steamscore
  tasks:
    -
      fail:
        msg: "Variable \"app_root\" is required"
      when: "app_root is not defined"
    -
      known_hosts:
        key: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
        name: github.com
        state: present
    -
      git:
        dest: "{{ app_root }}"
        repo: "git@github.com:SteamScore/api.git"
        version: "{{ git_commit }}"
    -
      composer:
        arguments: "--classmap-authoritative"
        command: install
        no_dev: yes
        optimize_autoloader: yes
        prefer_dist: yes
        working_dir: "{{ app_root }}"
  vars:
    git_commit: HEAD
